### ISSUE TITLE
Please create 1 unexecutable and 1 executable BoundedStartegyV2 on devnet

### ISSUE THREAD

**Issue by parhim** [mithraiclabs/poseidon#14] opened 2023-04-15 00:47 UTC
unexecutable meaning something at an unreasonably low price.

**Comment by tomjohn1028** [comment] 2023-04-15 17:48
Before I tackle the above, I'm thinking about the root cause of this issue. You want to test the new executor bot you are writing. 

Does the Jupiter API support devnet? 

If so, testing on Devnet might be the move. If not, and you’re just trying to test a small portion, then it might be best to test on a localnet. The integration tests have all the examples one would need to create Raydium or OpenBook markets on localnet.

**Comment by tomjohn1028** [comment] 2023-04-15 17:53
> [Jupiter] doesn’t support devnet

I'm going to remove this task from my ToDo. But here's some additional information that can help with testing. 

1. Checkout the [multileg trade test](https://github.com/mithraiclabs/poseidon/blob/master/tests/multiLeggedTrade.ts). Read all of the code and comments. It creates new mints, creates a new Raydium market, a new OpenBook DEX market, and adds liquidity. It does ALL of the setup needed to execute a trade. 
2. If you are going to write tests, then I would DRY the code instead of copy pasta. It is a lot of code. 
3. Read the anchor CLI [docs](https://www.anchor-lang.com/docs/cli). You can spin up a local chain that includes the programs and seeds that the tests do.

**Comment by tomjohn1028** [comment] 2023-04-15 17:55
Closing this as the original task is no longer required, but the information above should be helpful for localnet testing

**Closed as completed by tomjohn1028** 2023-04-15 17:55 UTC
